name: Run Databricks Notebook

on:
  push:
    branches: [ main ]  # or use 'master' if your repo uses that

jobs:
  run-notebook:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout repo
        uses: actions/checkout@v3

      - name: Run Databricks notebook
        uses: databricks/run-notebook@v0
        with:
          databricks-host: https://adb-1808066787890886.6.azuredatabricks.net
          databricks-token: ${{ secrets.DATABRICKS_TOKEN }}
          workspace-notebook-path: /Workspace/Users/rajvardhanshinde3003@gmail.com/SampleNotebook
          existing-cluster-id: 0808-100918-h03sh6sb
