name: Sync Notebooks → Databricks Workspace (per branch)

on:
  push:
    branches: [dev, ppe, main]
    paths:
      - "Notebooks/**"
      - "**/*.ipynb"
      - "**/*.py"
  workflow_dispatch: {}

concurrency:
  group: "dbx-sync-${{ github.ref_name }}"
  cancel-in-progress: true

jobs:
  sync:
    # Map branch -> environment name so we can use env-scoped secrets
    environment: ${{ github.ref_name == 'main' && 'prod' || github.ref_name }}
    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v4

      - uses: actions/setup-python@v5
        with:
          python-version: "3.11"

      - name: Install Databricks CLI
        run: pip install databricks-cli

      - name: Import Notebooks to workspace folder
        env:
          DATABRICKS_HOST: ${{ secrets.DATABRICKS_HOST }}
          DATABRICKS_TOKEN: ${{ secrets.DATABRICKS_TOKEN }}
          DEST_PATH: ${{ secrets.DEST_PATH }}   # workspace folder where you want files
        run: |
          set -euo pipefail
          if [ ! -d "Notebooks" ]; then
            echo "No Notebooks/ folder in repo. Nothing to sync."
            exit 0
          fi
          echo "Destination: ${DEST_PATH}"
          databricks workspace mkdirs "${DEST_PATH}"
          databricks workspace import-dir \
            --overwrite \
            --format AUTO \
            "Notebooks" "${DEST_PATH}"
          echo "✅ Synced Notebooks → ${DEST_PATH}"
