name: Deploy Databricks Bundle

on:
  push:
    branches: [dev, ppe, main]
    paths:
      - "Notebooks/**"
      - "**/*.ipynb"
      - "**/*.py"
      - "bundle.yml"
  workflow_dispatch: {}   # allow manual runs (e.g., hotfix/rollback)

concurrency:
  group: "dbx-bundle-${{ github.ref_name }}"
  cancel-in-progress: true

jobs:
  deploy:
    # main -> prod environment; otherwise use the branch name (dev/ppe)
    environment: ${{ github.ref_name == 'main' && 'prod' || github.ref_name }}
    runs-on: ubuntu-latest
    env:
      # These are read from the selected GitHub Environment (dev/ppe/prod)
      DATABRICKS_HOST:  ${{ secrets.DATABRICKS_HOST }}
      DATABRICKS_TOKEN: ${{ secrets.DATABRICKS_TOKEN }}
      TARGET: ${{ github.ref_name == 'main' && 'prod' || github.ref_name }}

    steps:
      - uses: actions/checkout@v4

      - name: Install Databricks CLI (new)
        run: |
          curl -fsSL https://raw.githubusercontent.com/databricks/setup-cli/main/install.sh | sh
          databricks --version

      - name: Sanity check (identity & workspace)
        run: |
          echo "Target: $TARGET"
          echo "Host:   $DATABRICKS_HOST"
          databricks current-user me -o json
          databricks workspace list / -o json

      - name: Validate bundle
        run: databricks bundle validate -t "$TARGET"

      - name: Deploy bundle
        run: databricks bundle deploy -t "$TARGET"
