name: Sync Notebooks → Databricks Workspace (per branch)

on:
  push:
    branches: [dev, ppe, main]
    paths:
      - "Notebooks/**"
      - "**/*.ipynb"
      - "**/*.py"
  workflow_dispatch: {}

concurrency:
  group: "dbx-sync-${{ github.ref_name }}"
  cancel-in-progress: true

jobs:
  sync:
    environment: ${{ github.ref_name == 'main' && 'prod' || github.ref_name }}
    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v4

      - name: Install Databricks CLI
        run: |
          curl -fsSL https://raw.githubusercontent.com/databricks/setup-cli/main/install.sh | sh
          databricks --version

      - name: Deploy Databricks Asset Bundle
        env:
          DATABRICKS_TOKEN: ${{ secrets.DATABRICKS_TOKEN }}
        run: |
          set -euo pipefail

          if [ "${{ github.ref_name }}" == "main" ]; then
            TARGET_ENV="prod"
            DEST_PATH="${{ secrets.DEST_PATH_PROD }}"
          elif [ "${{ github.ref_name }}" == "ppe" ]; then
            TARGET_ENV="ppe"
            DEST_PATH="${{ secrets.DEST_PATH_PPE }}"
          else
            TARGET_ENV="dev"
            DEST_PATH="${{ secrets.DEST_PATH_DEV }}"
          fi

          echo "Validating bundle for ${TARGET_ENV}"
          databricks bundle validate -t ${TARGET_ENV} --var="root_path=${DEST_PATH}"

          echo "Deploying bundle to ${TARGET_ENV} target"
          databricks bundle deploy -t ${TARGET_ENV} --var="root_path=${DEST_PATH}"
